name: Auto-asignar a Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Añadir Issue al Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Yelose/projects/19
          github-token: ${{ secrets.PROJECT_PAT }}
